# Generated by Django 4.1.7 on 2023-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0008_remove_product_tags_remove_tag_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgconnector',
            old_name='img',
            new_name='image',
        ),
    ]
