# Generated by Django 4.1.7 on 2023-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0009_rename_img_imgconnector_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagConnection',
            new_name='TagConnector',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, through='ShopApp.TagConnector', to='ShopApp.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
