# Generated by Django 4.1.7 on 2023-04-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0012_rename_image_imgconnector_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgconnector',
            old_name='img',
            new_name='mainimage',
        ),
    ]
